Все требования ТЗ 13 выполнены
VasilyNS/java-shareit pull request #1
Opened 2023-05-08 07:45 UTC by VasilyNS

Сергей, привет! ) 

В новом проекте всё логирование выполнено по твой рекомендации, сначала в контроллере (begin), потом при окончании работы бизнес-логики перед возвратом данных через API (end). 

Вроде код максимально чистый, есть небольшие заглушки для следующих спринтов.

2023-05-10 03:35 UTC, krylov-sergey-sergeevich requested changes
Привет, в целом неплохая работа, давай поправим то что отметил и еще пару моментов:

1) Учесть и поправить нейминг методов: get - это или получение объекта или исключение, find - это или объект или null
2) Давай создадим специальное исключение UserFoundException наследника NotFoundException и сделаем так чтобы каждый раз не повторять текст:
() -> new UserFoundException(userId));

p.s для остальных исключений тоже можно подумать в эту сторону ...


Буду ждать с правками =)

2023-05-10 03:35 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/practicum/shareit/booking/Bs.java
> +public enum Bs {
Не очень название класса - давай сделаем его побольше и понятнее

2023-05-10 03:35 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/practicum/shareit/item/Item.java
> +    private int id;
private Long id;

2023-05-10 03:35 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/practicum/shareit/user/UserDaoImpl.java
> +    private List<User> users = new ArrayList<>();
Лист это самая эффективная структура хранения?

2023-05-10 09:19 UTC, VasilyNS commented on src/main/java/ru/practicum/shareit/user/UserDaoImpl.java
> +    private List<User> users = new ArrayList<>();
В данном случае - очень даже! Очень эффективно по занимаемой оперативной памяти, добавление - очень быстрое o(1). Получение полного списка для getAll - моментальное. Поиск по id - можно дописать через деление пополам, так как у нас id только растут, то есть уже отсортированы. Тоже будет очень эффективная логарифмическая зависимость от n. К тому же это временный вариант перед хранением в БД и в ТЗ не сказано про эффективность ))

2023-05-10 09:22 UTC, VasilyNS commented on src/main/java/ru/practicum/shareit/booking/Bs.java
> +public enum Bs {
Если часто ипользовать, как приставку для констант enum, то нормально, видел в проектах такое. Тем более там java.doc, всё понятно. Но переделал на BookingStatus )

2023-05-10 09:32 UTC, VasilyNS commented on src/main/java/ru/practicum/shareit/item/Item.java
> +    private int id;
Готово, переписал везде в проекте чтобы id были не int, а Long

2023-05-10 09:51 UTC, VasilyNS commented
> 1. Учесть и поправить нейминг методов: get - это или получение объекта или исключение, find - это или объект или null

findAllByOwner(ownerId) по ТЗ не уточнено, должно ли вызывать исключение, если нет такого владельца. В тестах постмана этого тоже нет. Возможно это должен быть просто пустой список. Но пусть будет get. Остальные find тоже не возвращают null, а пустой список по постману. Но переименую в get.

> 2. Давай создадим специальное исключение UserFoundException наследника NotFoundException и сделаем так чтобы каждый раз не повторять текст:
>    () -> new UserFoundException(userId));
> p.s для остальных исключений тоже можно подумать в эту сторону ...

Тут как посмотреть, если объектов будет 100500 то просто будет огромная куча абсолютно одинаковых классов. Тогда уж передавать текстом название класса объекта + id. В любом случае это открытый вопрос для руководителя проекта. Но пусть будет наследование ))

2023-05-11 11:12 UTC, krylov-sergey-sergeevich approved these changes
Привет, вижу правки - зачет!

2023-05-12 06:24 UTC, merged